# **nalara.academy**

## **Modul 1 - Fundamental Python & Computational Thinking**

### **📌 Pengantar Modul**

Banyak orang gagal belajar pemrograman bukan karena kodenya yang rumit, melainkan karena mereka langsung melompat ke sintaksis tanpa membangun logika berpikir komputer (*computational thinking*). Di era kecerdasan buatan, kode program bukan lagi sekadar teks yang diketik, melainkan instruksi logis untuk memecahkan masalah.

Modul 1 ini didesain khusus sebagai batu pijakan pertama Anda memasuki dunia teknologi. Kita akan membedah dasar-dasar bahasa pemrograman Python dari nol—mulai dari bagaimana komputer mengeksekusi *bytecode*, memanipulasi memori lewat variabel, mengendalikan logika keputusan dan perulangan, beralih ke matematika komputasi matriks dengan NumPy, hingga memahami arsitektur perangkat lunak modern melalui paradigma *Object-Oriented Programming* (OOP). Seluruh materi dirancang secara interaktif, mengedepankan intuisi lewat analogi sehari-hari, dan menjadi fondasi wajib sebelum Anda melangkah ke modul *Data Science* maupun *Computer Vision*.

---

### **🗺️ Peta Perjalanan Belajar (Learning Roadmap)**

* 📁 **Sesi 1: Fundamental, Tipe Data, & Struktur Data**
* **Fokus:** Memahami cara kerja eksekusi program Python, aturan komparasi memori, serta bagaimana komputer mengelola data dinamis (`List`) dan struktural (`Dictionary`).
* **Output Praktis:** Mampu mengelola tipe data dasar, melakukan *casting* variabel, memanipulasi teks (*string alignment*), dan menyusun database biodata peserta secara rapi.


* 📊 **Sesi 2: Control Flow & Fungsi Terapan**
* **Fokus:** Memberikan logika keputusan pada program (`if-elif-else`) serta otomatisasi tugas repetitif lewat kontrol perulangan (`for`, `while`, `break`, `continue`).
* **Output Praktis:** Mampu menulis skrip penyaringan (*filter*) data otomatis, menyusun kalkulator interaktif, lalu membungkusnya ke dalam Fungsi modular menggunakan parameter lanjut (`*args` dan `kwargs`).


* 📏 **Sesi 3: Pengantar Library, Array, dan Matriks dengan NumPy**
* **Fokus:** Akselerasi komputasi dari Python murni menuju pengolahan matriks berbasis C (Vektorisasi). Memahami struktur Array 1D dan Matriks 2D demi fondasi manipulasi piksel.
* **Output Praktis:** Mampu membuat array tingkat lanjut, melakukan operasi aritmatika matriks, manipulasi dimensi (*shape manipulation* & *stacking*), hingga menyelesaikan operasi linear (Dot, Cross, Invers).


* 🗑️ **Sesi 4: Pengantar OOP (Object-Oriented Programming) & Mini Project**
* **Fokus:** Memahami cetak biru perangkat lunak modern melalui enkapsulasi (*private variables*, *getter-setter*), pewarisan sifat (*inheritance*), hingga abstraksi logika objek.
* **Output Praktis:** Mampu mengimplementasikan *magic methods* dan merancang proyek akhir berupa aplikasi "Kasir Toko & Inventaris Mandiri" yang interaktif.

## **📁 Sesi 1: Fundamental, Tipe Data, & Struktur Data**

### **1.1 Bagaimana Python Bekerja?**

Sebelum menulis kode, kita harus tahu apa yang terjadi di balik layar. Python adalah bahasa *interpreted*. Saat Anda menjalankan file `.py`, Python interpreter akan menerjemahkan baris kodemu menjadi **Bytecode** (disimpan di folder `__pycache__` sebagai file `.pyc`). Komputer tidak paham bahasa manusia, dan *Bytecode* inilah yang dibaca oleh *Python Virtual Machine* (PVM) agar instruksi kita bisa dieksekusi oleh prosesor.

### **1.2 Variabel, Tipe Data, dan Mekanisme Casting**

**Variabel** adalah nama penanda sebuah lokasi di memori komputer untuk menyimpan nilai data. Di Python, variabel bersifat dinamis (tidak perlu mendeklarasikan tipe datanya secara manual).

Tipe data dasar yang wajib dipahami:

* **`String` (Teks):** Karakter yang diapit kutip. Python mendukung *multiline string* (`"""`) dan *Literal String* (`f"..."`) untuk mempermudah format teks.
* **`Integer` (Angka Bulat):** Bilangan tanpa desimal (Contoh: `10`, `-3`).
* **`Float` (Angka Desimal):** Bilangan pecahan dengan titik desimal (Contoh: `3.14`).
* **`Boolean` (Logika):** Hanya bernilai `True` atau `False`.

**Mekanisme Casting:** Kadang data yang kita terima dari pengguna lewat fungsi `input()` selalu bertipe *String*. **Casting** adalah proses memaksa suatu tipe data berubah menjadi tipe data lain (misal: mengubah `"100"` menjadi `100` menggunakan fungsi `int()`).

### **1.3 Operator Komparasi Kompleks & Bitwise**

Komputer mengambil keputusan berdasarkan perbandingan. Selain operator matematika biasa (`+`, `-`, `*`, `/`), Python memiliki operator komparasi khusus:

* **Operator `is` dan `is not`:** Berbeda dengan `==` yang hanya memeriksa *nilai* objek, operator `is` digunakan untuk memeriksa apakah dua variabel menunjuk ke **alamat memori (object identity) yang sama**.

**Operator Bitwise:** Operator yang melakukan komputasi langsung di tingkat biner (bit per bit). Digunakan untuk optimasi performa tingkat tinggi pada algoritma data:

* `&` (AND), `|` (OR), `^` (XOR), `~` (NOT), serta Shifting (`<<`, `>>`).

### **1.4 Struktur Data Lanjutan: List, Tuple, Set, dan Dictionary**

Ketika mengelola ribuan data, variabel tunggal tidak akan cukup. Kita membutuhkan koleksi data:

1. **`List` (Keranjang Belanja Dinamis):** Koleksi data berurutan menggunakan tanda `[]`. Elemennya bisa dimanipulasi, ditambah (`.append()`), atau disisipkan (`.insert()`). Python juga mendukung *Nested List* (List di dalam List) yang menjadi cikal bakal visualisasi tabel data.
2. **`Tuple` & `Set`:** `Tuple` `()` bersifat *immutable* (isinya dikunci dan tidak bisa diubah setelah dibuat), sangat aman untuk data konstan. `Set` `{}` adalah kumpulan data unik tanpa duplikasi dan tidak berurutan.
3. **`Dictionary` (Buku Kontak Key-Value):** Koleksi data menggunakan kurung kurawal `{}` yang berpasangan. Data dicari berdasarkan **Key** (Kata Kunci), bukan nomor indeks. Sangat cocok untuk memetakan database profil atau biodata terstruktur.


### **💻 Praktik 1: Variabel, Tipe Data, & Mekanisme Casting**

Sebelum membuat program yang kompleks, kita harus terbiasa dulu dengan
"bahan baku" paling dasar dalam pemrograman: variabel dan tipe data.

Di praktik ini kita akan:
- Membuat variabel dengan berbagai tipe data (String, Integer, Float, Boolean)
- Memeriksa tipe data sebuah variabel menggunakan `type()`
- Mempraktikkan *casting* — mengubah satu tipe data menjadi tipe data lain

In [76]:
# Variabel bertipe String (teks)
nama = "Andi"

# Variabel bertipe Integer (angka bulat)
umur = 20

# Variabel bertipe Float (angka desimal)
tinggi_badan = 172.5

# Variabel bertipe Boolean (logika True/False)
sudah_lulus = False

# Cek tipe data dari setiap variabel menggunakan type()
print(f"nama          : {nama}          -> tipe data: {type(nama)}")
print(f"umur          : {umur}          -> tipe data: {type(umur)}")
print(f"tinggi_badan  : {tinggi_badan}  -> tipe data: {type(tinggi_badan)}")
print(f"sudah_lulus   : {sudah_lulus}   -> tipe data: {type(sudah_lulus)}")

nama          : Andi          -> tipe data: <class 'str'>
umur          : 20          -> tipe data: <class 'int'>
tinggi_badan  : 172.5  -> tipe data: <class 'float'>
sudah_lulus   : False   -> tipe data: <class 'bool'>


In [77]:
# Multiline string menggunakan tiga tanda kutip
biodata = """
Nama         : Andi
Umur         : 20 tahun
Tinggi Badan : 172.5 cm
"""
print(biodata)

# f-string (Literal String) untuk menyisipkan variabel langsung ke dalam teks
print(f"Halo, nama saya {nama}. Saya berusia {umur} tahun.")


Nama         : Andi
Umur         : 20 tahun
Tinggi Badan : 172.5 cm

Halo, nama saya Andi. Saya berusia 20 tahun.


In [78]:
# Simulasikan input dari pengguna -- hasil input() SELALU bertipe String
umur_input = "20"
print(f"Sebelum casting -> nilai: {umur_input}, tipe data: {type(umur_input)}")

# Casting String menjadi Integer menggunakan int()
umur_setelah_casting = int(umur_input)
print(f"Setelah casting -> nilai: {umur_setelah_casting}, tipe data: {type(umur_setelah_casting)}")

# Casting Integer menjadi Float
nilai_float = float(umur_setelah_casting)
print(f"Casting ke Float -> nilai: {nilai_float}, tipe data: {type(nilai_float)}")

# Casting angka menjadi String (kebalikannya)
nilai_string = str(umur_setelah_casting)
print(f"Casting ke String -> nilai: {nilai_string}, tipe data: {type(nilai_string)}")

Sebelum casting -> nilai: 20, tipe data: <class 'str'>
Setelah casting -> nilai: 20, tipe data: <class 'int'>
Casting ke Float -> nilai: 20.0, tipe data: <class 'float'>
Casting ke String -> nilai: 20, tipe data: <class 'str'>


In [79]:
# Casting tidak selalu berhasil -- coba casting teks yang bukan angka
teks_invalid = "dua puluh"

try:
    hasil = int(teks_invalid)
    print(f"Berhasil di-casting: {hasil}")
except ValueError as e:
    print(f"❌ Gagal melakukan casting! Error: {e}")
    print("   Penyebab: teks 'dua puluh' tidak bisa diubah langsung menjadi angka.")

❌ Gagal melakukan casting! Error: invalid literal for int() with base 10: 'dua puluh'
   Penyebab: teks 'dua puluh' tidak bisa diubah langsung menjadi angka.


### **💻 Praktik 2: Operator Komparasi (`==` vs `is`) & Bitwise**

Komputer mengambil keputusan berdasarkan perbandingan. Di praktik ini kita
akan membedah perbedaan antara `==` (membandingkan **nilai**) dan `is`
(membandingkan **identitas objek di memori**), lalu mencoba operator
Bitwise yang bekerja langsung di level biner.

In [80]:
# Dua variabel dengan nilai yang sama
a = 100
b = 100

print(f"a = {a}, b = {b}")
print(f"a == b -> {a == b}   (membandingkan NILAI)")
print(f"a is b -> {a is b}   (membandingkan ALAMAT MEMORI)")
print(f"id(a)  -> {id(a)}")
print(f"id(b)  -> {id(b)}")

a = 100, b = 100
a == b -> True   (membandingkan NILAI)
a is b -> True   (membandingkan ALAMAT MEMORI)
id(a)  -> 140713498685656
id(b)  -> 140713498685656


In [81]:
# Dua List dengan isi yang identik, tapi dibuat secara terpisah
list_a = [1, 2, 3]
list_b = [1, 2, 3]

# List yang menunjuk ke objek yang SAMA di memori
list_c = list_a

print(f"list_a == list_b -> {list_a == list_b}   (nilainya sama)")
print(f"list_a is list_b -> {list_a is list_b}   (objek BEDA di memori)")
print(f"list_a is list_c -> {list_a is list_c}   (objek SAMA, karena list_c = list_a)")

print()
print(f"id(list_a) -> {id(list_a)}")
print(f"id(list_b) -> {id(list_b)}")
print(f"id(list_c) -> {id(list_c)}")

list_a == list_b -> True   (nilainya sama)
list_a is list_b -> False   (objek BEDA di memori)
list_a is list_c -> True   (objek SAMA, karena list_c = list_a)

id(list_a) -> 1719865490752
id(list_b) -> 1719865490816
id(list_c) -> 1719865490752


In [82]:
x = 12   # dalam biner: 1100
y = 10   # dalam biner: 1010

print(f"x = {x:>3} -> biner: {bin(x)}")
print(f"y = {y:>3} -> biner: {bin(y)}")
print("=" * 35)

print(f"x & y  (AND)   -> {x & y:>3}  | biner: {bin(x & y)}")
print(f"x | y  (OR)    -> {x | y:>3}  | biner: {bin(x | y)}")
print(f"x ^ y  (XOR)   -> {x ^ y:>3}  | biner: {bin(x ^ y)}")
print(f"~x     (NOT)   -> {~x:>3}  | biner: {bin(~x)}")

x =  12 -> biner: 0b1100
y =  10 -> biner: 0b1010
x & y  (AND)   ->   8  | biner: 0b1000
x | y  (OR)    ->  14  | biner: 0b1110
x ^ y  (XOR)   ->   6  | biner: 0b110
~x     (NOT)   -> -13  | biner: -0b1101


In [83]:
angka = 4   # biner: 100

print(f"angka asli       : {angka} -> biner: {bin(angka)}")
print(f"angka << 1 (Left Shift)  : {angka << 1} -> biner: {bin(angka << 1)}   (nilai x2)")
print(f"angka << 2 (Left Shift)  : {angka << 2} -> biner: {bin(angka << 2)}   (nilai x4)")
print(f"angka >> 1 (Right Shift) : {angka >> 1} -> biner: {bin(angka >> 1)}   (nilai dibagi 2)")

angka asli       : 4 -> biner: 0b100
angka << 1 (Left Shift)  : 8 -> biner: 0b1000   (nilai x2)
angka << 2 (Left Shift)  : 16 -> biner: 0b10000   (nilai x4)
angka >> 1 (Right Shift) : 2 -> biner: 0b10   (nilai dibagi 2)


### **💻 Praktik 3: List (Keranjang Dinamis) & Tuple (Data Terkunci)**

Di praktik ini kita akan membandingkan dua struktur data berurutan yang
paling sering dipakai: `List` yang fleksibel dan bisa diubah-ubah, serta
`Tuple` yang sifatnya terkunci (*immutable*) dan aman untuk data konstan.
Kita juga akan mencoba *Nested List* — List di dalam List — sebagai
cikal bakal representasi tabel data.

In [84]:
# List awal berisi daftar belanja
belanjaan = ["beras", "telur", "minyak"]
print(f"List awal      : {belanjaan}")

# .append() -> menambah elemen di akhir List
belanjaan.append("gula")
print(f"Setelah append : {belanjaan}")

# .insert(posisi, nilai) -> menyisipkan elemen di posisi tertentu
belanjaan.insert(1, "sabun")
print(f"Setelah insert : {belanjaan}")

# .remove() -> menghapus elemen berdasarkan nilainya
belanjaan.remove("minyak")
print(f"Setelah remove : {belanjaan}")

# Indexing & slicing List
print(f"\nElemen pertama        : {belanjaan[0]}")
print(f"Elemen terakhir        : {belanjaan[-1]}")
print(f"Dua elemen pertama     : {belanjaan[0:2]}")

List awal      : ['beras', 'telur', 'minyak']
Setelah append : ['beras', 'telur', 'minyak', 'gula']
Setelah insert : ['beras', 'sabun', 'telur', 'minyak', 'gula']
Setelah remove : ['beras', 'sabun', 'telur', 'gula']

Elemen pertama        : beras
Elemen terakhir        : gula
Dua elemen pertama     : ['beras', 'sabun']


In [85]:
# Nested List -> List yang setiap elemennya juga berupa List
# Setiap baris merepresentasikan satu data: [nama, umur, kota]
data_peserta = [
    ["Andi", 20, "Bandung"],
    ["Sari", 22, "Jakarta"],
    ["Budi", 19, "Surabaya"]
]

print("📋 Tabel Data Peserta:")
print("-" * 35)
for baris in data_peserta:
    nama, umur, kota = baris  # unpacking otomatis
    print(f"Nama: {nama:<6} | Umur: {umur:<3} | Kota: {kota}")
print("-" * 35)

# Mengakses elemen spesifik di dalam Nested List
# data_peserta[1] -> baris kedua, data_peserta[1][0] -> nama di baris kedua
print(f"\nNama peserta baris ke-2 : {data_peserta[1][0]}")

📋 Tabel Data Peserta:
-----------------------------------
Nama: Andi   | Umur: 20  | Kota: Bandung
Nama: Sari   | Umur: 22  | Kota: Jakarta
Nama: Budi   | Umur: 19  | Kota: Surabaya
-----------------------------------

Nama peserta baris ke-2 : Sari


In [86]:
# Tuple cocok untuk data yang tidak boleh berubah, misal koordinat tetap
koordinat = (10, 20)
print(f"Tuple koordinat: {koordinat}")
print(f"Tipe data      : {type(koordinat)}")

# Coba ubah isi Tuple -> akan menghasilkan error
try:
    koordinat[0] = 99
except TypeError as e:
    print(f"\n❌ Gagal mengubah Tuple! Error: {e}")
    print("   Penyebab: Tuple bersifat immutable, isinya terkunci permanen.")

Tuple koordinat: (10, 20)
Tipe data      : <class 'tuple'>

❌ Gagal mengubah Tuple! Error: 'tuple' object does not support item assignment
   Penyebab: Tuple bersifat immutable, isinya terkunci permanen.


In [87]:
import sys

list_contoh  = [1, 2, 3, 4, 5]
tuple_contoh = (1, 2, 3, 4, 5)

print(f"Ukuran memori List  : {sys.getsizeof(list_contoh)} bytes")
print(f"Ukuran memori Tuple : {sys.getsizeof(tuple_contoh)} bytes")
print("\n💡 Tuple cenderung lebih ringan di memori karena sifatnya yang terkunci,")
print("   sehingga Python tidak perlu menyiapkan ruang ekstra untuk perubahan data.")

Ukuran memori List  : 104 bytes
Ukuran memori Tuple : 88 bytes

💡 Tuple cenderung lebih ringan di memori karena sifatnya yang terkunci,
   sehingga Python tidak perlu menyiapkan ruang ekstra untuk perubahan data.


### **💻 Praktik 4: Set (Data Unik) & Dictionary (Database Key-Value)**

Di praktik terakhir Sesi 1 ini, kita akan mengenal `Set` — struktur data
yang otomatis menghapus duplikasi, dan `Dictionary` — struktur data yang
mencari informasi berdasarkan **Key** (kata kunci), bukan nomor indeks.
Dictionary inilah yang akan kita gunakan untuk menyusun database biodata
peserta secara rapi dan terstruktur.

In [88]:
# List yang sengaja punya data duplikat
kota_asal_peserta = ["Jakarta", "Bandung", "Jakarta", "Surabaya", "Bandung", "Jakarta"]
print(f"List asli (dengan duplikat) : {kota_asal_peserta}")
print(f"Jumlah data                : {len(kota_asal_peserta)}")

# Mengubah List menjadi Set -> duplikat otomatis terhapus
kota_unik = set(kota_asal_peserta)
print(f"\nSet hasil konversi (unik)  : {kota_unik}")
print(f"Jumlah data unik           : {len(kota_unik)}")

print("\n💡 Set sangat berguna untuk menghitung jumlah kategori unik")
print("   dari ribuan data tanpa perlu mengecek satu per satu secara manual.")

List asli (dengan duplikat) : ['Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung', 'Jakarta']
Jumlah data                : 6

Set hasil konversi (unik)  : {'Jakarta', 'Bandung', 'Surabaya'}
Jumlah data unik           : 3

💡 Set sangat berguna untuk menghitung jumlah kategori unik
   dari ribuan data tanpa perlu mengecek satu per satu secara manual.


In [89]:
# Dictionary menggunakan pasangan Key (kata kunci) dan Value (nilai)
biodata_andi = {
    "nama": "Andi",
    "umur": 20,
    "kota": "Bandung",
    "hobi": ["Coding", "Membaca", "Futsal"]  # Value boleh berupa List
}

print("📋 Biodata Peserta:")
print("-" * 30)
# Mengakses nilai menggunakan Key, BUKAN nomor indeks
print(f"Nama : {biodata_andi['nama']}")
print(f"Umur : {biodata_andi['umur']}")
print(f"Kota : {biodata_andi['kota']}")
print(f"Hobi : {', '.join(biodata_andi['hobi'])}")

# Menambah Key baru ke Dictionary yang sudah ada
biodata_andi["status"] = "Aktif"
print(f"\nSetelah menambah key baru: {biodata_andi}")

📋 Biodata Peserta:
------------------------------
Nama : Andi
Umur : 20
Kota : Bandung
Hobi : Coding, Membaca, Futsal

Setelah menambah key baru: {'nama': 'Andi', 'umur': 20, 'kota': 'Bandung', 'hobi': ['Coding', 'Membaca', 'Futsal'], 'status': 'Aktif'}


In [90]:
# Database biodata banyak peserta -> Dictionary di dalam Dictionary
database_peserta = {
    "P001": {"nama": "Andi", "umur": 20, "kota": "Bandung"},
    "P002": {"nama": "Sari", "umur": 22, "kota": "Jakarta"},
    "P003": {"nama": "Budi", "umur": 19, "kota": "Surabaya"}
}

print("📋 DATABASE BIODATA PESERTA")
print("=" * 45)

# .items() -> mengambil sepasang Key dan Value sekaligus saat looping
for id_peserta, data in database_peserta.items():
    print(f"\n🆔 ID Peserta : {id_peserta}")
    for key, value in data.items():
        print(f"   {key.capitalize():<6} : {value}")

print("\n" + "=" * 45)
print(f"Total peserta terdaftar : {len(database_peserta)} orang")

📋 DATABASE BIODATA PESERTA

🆔 ID Peserta : P001
   Nama   : Andi
   Umur   : 20
   Kota   : Bandung

🆔 ID Peserta : P002
   Nama   : Sari
   Umur   : 22
   Kota   : Jakarta

🆔 ID Peserta : P003
   Nama   : Budi
   Umur   : 19
   Kota   : Surabaya

Total peserta terdaftar : 3 orang


In [91]:
# Mencari biodata peserta berdasarkan ID -- jauh lebih cepat dibanding
# mencari satu-satu di dalam List biasa
id_dicari = "P002"

# Menggunakan .get() lebih aman dibanding [] karena tidak akan error
# jika Key-nya tidak ditemukan
hasil_cari = database_peserta.get(id_dicari)

if hasil_cari:
    print(f"✅ Data ditemukan untuk ID {id_dicari}:")
    print(f"   Nama : {hasil_cari['nama']}")
    print(f"   Umur : {hasil_cari['umur']}")
    print(f"   Kota : {hasil_cari['kota']}")
else:
    print(f"❌ Data dengan ID {id_dicari} tidak ditemukan.")

✅ Data ditemukan untuk ID P002:
   Nama : Sari
   Umur : 22
   Kota : Jakarta


## **📊 Sesi 2: Control Flow & Fungsi Terapan**

### **2.1 Cabang Keputusan Dinamis (If-Elif-Else)**

**Control Flow** memberikan "otak" bagi program untuk memilih jalur eksekusi kode berdasarkan kondisi logika `True` atau `False`.

* Di Python, blok percabangan ditandai secara mutlak menggunakan **Indentasi** (spasi/tab), bukan tanda kurung kurawal.

### **2.2 Kontrol Perulangan Tingkat Lanjut (Loops Control)**

Perulangan digunakan agar komputer mengeksekusi perintah repetitif secara otomatis:

* **`for` loop:** Iterasi terukur melewati objek koleksi (seperti List atau fungsi `range()`). Kita bisa mengekstrak nilai sekaligus posisinya memanfaatkan fungsi `enumerate()`.
* **`while` loop:** Perulangan bersyarat yang akan berjalan terus selama kondisinya masih terpenuhi.

**Keywords Pengendali Loop:**

* `pass`: Statemen kosong sebagai *placeholder* agar kode tidak error saat belum diisi logika.
* `continue`: Melewati sisa baris kode di dalam loop pada perulangan saat ini dan langsung meloncat ke iterasi berikutnya.
* `break`: Menghentikan paksa seluruh aktivitas perulangan secara instan, meskipun kondisi utama loop masih bernilai benar.

### **2.3 Modularitas Kode: Fungsi Terapan, `*args`, & `kwargs**`

Fungsi (`def`) adalah blok kode mandiri yang dirancang untuk melakukan tugas spesifik. Agar fungsi kita fleksibel menampung jumlah input yang tidak pasti, kita menggunakan fitur parameter tingkat lanjut:

* **`*args` (Arguments):** Menerima input parameter dalam jumlah berapapun dan membungkusnya secara otomatis menjadi sebuah **Tuple**.
* **`kwargs` (Keyword Arguments):** Menerima input parameter acak yang memiliki nama variabel, lalu membungkusnya secara otomatis menjadi sebuah **Dictionary**.

### **💻 Praktik 1: Cabang Keputusan Dinamis (If-Elif-Else)**

`Control Flow` memberi "otak" bagi program untuk memilih jalur eksekusi
berdasarkan kondisi `True` atau `False`. Di praktik ini kita akan membuat
program penentu nilai (grading) — semakin kompleks aturannya, semakin
banyak cabang `elif` yang dibutuhkan.

Ingat: blok kode di Python ditandai dengan **Indentasi**, bukan tanda
kurung kurawal seperti bahasa lain.

In [92]:
# Kondisi paling dasar: apakah nilai sudah lulus standar minimum?
nilai = 75
standar_lulus = 60

if nilai >= standar_lulus:
    print(f"Nilai {nilai} -> LULUS ✅")
else:
    print(f"Nilai {nilai} -> TIDAK LULUS ❌")

Nilai 75 -> LULUS ✅


In [93]:
nilai = 87

if nilai >= 90:
    grade = "A"
elif nilai >= 80:
    grade = "B"
elif nilai >= 70:
    grade = "C"
elif nilai >= 60:
    grade = "D"
else:
    grade = "E"

print(f"Nilai  : {nilai}")
print(f"Grade  : {grade}")

Nilai  : 87
Grade  : B


In [94]:
# Program penentu kelayakan beasiswa
nilai_akademik = 88
penghasilan_ortu = 2_500_000  # dalam Rupiah
batas_penghasilan = 3_000_000

if nilai_akademik >= 85 and penghasilan_ortu <= batas_penghasilan:
    print("✅ LAYAK menerima beasiswa penuh.")
elif nilai_akademik >= 75 or penghasilan_ortu <= batas_penghasilan:
    print("⚠️  LAYAK menerima beasiswa sebagian.")
else:
    print("❌ TIDAK LAYAK menerima beasiswa.")

print(f"\nDetail -> Nilai akademik: {nilai_akademik}, Penghasilan ortu: Rp{penghasilan_ortu:,}")

✅ LAYAK menerima beasiswa penuh.

Detail -> Nilai akademik: 88, Penghasilan ortu: Rp2,500,000


In [95]:
# Program verifikasi akun sederhana
username_input = "admin"
password_input = "rahasia123"

username_valid = "admin"
password_valid = "rahasia123"

if username_input == username_valid:
    print("✅ Username ditemukan.")
    if password_input == password_valid:
        print("✅ Password benar -> LOGIN BERHASIL")
    else:
        print("❌ Password salah -> LOGIN GAGAL")
else:
    print("❌ Username tidak ditemukan -> LOGIN GAGAL")

✅ Username ditemukan.
✅ Password benar -> LOGIN BERHASIL


### **💻 Praktik 2: Kontrol Perulangan & Filter Data Otomatis**

Perulangan (`for` dan `while`) memungkinkan komputer mengeksekusi perintah
repetitif secara otomatis tanpa kita menulis kode yang sama berulang-ulang.
Ditambah dengan keyword pengendali `pass`, `continue`, dan `break`, kita bisa
membuat program penyaring (*filter*) data secara otomatis dari ribuan baris data.

In [96]:
buah = ["apel", "jeruk", "mangga", "anggur"]

print("🍎 Daftar Buah:")
for buah_item in buah:
    print(f"- {buah_item}")

print("\n🍎 Daftar Buah dengan Nomor Urut (enumerate):")
# enumerate() mengekstrak nilai SEKALIGUS posisinya (index)
for nomor, buah_item in enumerate(buah, start=1):
    print(f"{nomor}. {buah_item}")

🍎 Daftar Buah:
- apel
- jeruk
- mangga
- anggur

🍎 Daftar Buah dengan Nomor Urut (enumerate):
1. apel
2. jeruk
3. mangga
4. anggur


In [97]:
# Filter otomatis: cetak hanya angka GANJIL, lewati angka genap
angka_list = list(range(1, 11))  # 1 sampai 10

print("Memproses daftar angka 1-10, hanya menampilkan yang GANJIL:")
for angka in angka_list:
    if angka % 2 == 0:
        continue  # lewati sisa baris kode, lanjut ke iterasi berikutnya
    print(f"-> {angka} adalah angka ganjil")

Memproses daftar angka 1-10, hanya menampilkan yang GANJIL:
-> 1 adalah angka ganjil
-> 3 adalah angka ganjil
-> 5 adalah angka ganjil
-> 7 adalah angka ganjil
-> 9 adalah angka ganjil


In [98]:
# Mencari nilai tertentu di dalam List, berhenti begitu ketemu
stok_barang = ["Pulpen", "Buku", "Penghapus", "Pensil", "Penggaris"]
barang_dicari = "Pensil"

print(f"Mencari '{barang_dicari}' di dalam stok...")
for index, barang in enumerate(stok_barang):
    print(f"Memeriksa index {index}: {barang}")
    if barang == barang_dicari:
        print(f"✅ Ditemukan di index {index}! Pencarian dihentikan.")
        break  # hentikan loop, tidak perlu cek sisa data

Mencari 'Pensil' di dalam stok...
Memeriksa index 0: Pulpen
Memeriksa index 1: Buku
Memeriksa index 2: Penghapus
Memeriksa index 3: Pensil
✅ Ditemukan di index 3! Pencarian dihentikan.


In [99]:
# pass digunakan saat logika belum siap, tapi kode tetap harus bisa berjalan
status_list = ["aktif", "nonaktif", "pending", "aktif"]

for status in status_list:
    if status == "aktif":
        print(f"Status '{status}' -> proses lebih lanjut")
    elif status == "nonaktif":
        pass  # logika untuk status nonaktif belum diimplementasikan
    else:
        print(f"Status '{status}' -> menunggu konfirmasi")

print("\n💡 'pass' membiarkan program tetap berjalan normal")
print("   meskipun logikanya belum diisi sama sekali.")

Status 'aktif' -> proses lebih lanjut
Status 'pending' -> menunggu konfirmasi
Status 'aktif' -> proses lebih lanjut

💡 'pass' membiarkan program tetap berjalan normal
   meskipun logikanya belum diisi sama sekali.


In [100]:
# Studi kasus: saring peserta yang lolos seleksi (umur >= 18 DAN nilai >= 70)
data_calon_peserta = [
    {"nama": "Andi", "umur": 20, "nilai": 85},
    {"nama": "Sari", "umur": 17, "nilai": 90},
    {"nama": "Budi", "umur": 19, "nilai": 60},
    {"nama": "Dewi", "umur": 22, "nilai": 75},
]

peserta_lolos = []

for calon in data_calon_peserta:
    if calon["umur"] < 18:
        continue  # otomatis tidak lolos, skip langsung
    if calon["nilai"] < 70:
        continue  # nilai kurang, skip juga
    peserta_lolos.append(calon["nama"])

print("📋 HASIL FILTER SELEKSI PESERTA")
print(f"Total calon   : {len(data_calon_peserta)} orang")
print(f"Lolos seleksi : {len(peserta_lolos)} orang")
print(f"Nama yang lolos: {peserta_lolos}")

📋 HASIL FILTER SELEKSI PESERTA
Total calon   : 4 orang
Lolos seleksi : 2 orang
Nama yang lolos: ['Andi', 'Dewi']


In [101]:
# Simulasi countdown menggunakan while loop
hitungan = 5

print("Memulai countdown:")
while hitungan > 0:
    print(f"{hitungan}...")
    hitungan -= 1  # kurangi 1 setiap iterasi, WAJIB agar tidak infinite loop

print("🚀 Mulai!")

Memulai countdown:
5...
4...
3...
2...
1...
🚀 Mulai!


### **💻 Praktik 3: Kalkulator Interaktif dengan While Loop**

Sekarang kita gabungkan semua yang sudah dipelajari — `while` loop,
`if-elif-else`, casting, dan `break` — untuk membuat sebuah program
kalkulator sederhana yang bisa terus digunakan berulang kali sampai
pengguna sendiri yang memutuskan untuk berhenti.

In [102]:
# Definisikan dulu logika operasi matematikanya secara terpisah
def hitung(angka1, operator, angka2):
    """
    Menerima dua angka dan satu operator, mengembalikan hasil perhitungan.
    Jika operator tidak dikenali atau ada error matematika, kembalikan None.
    """
    if operator == "+":
        return angka1 + angka2
    elif operator == "-":
        return angka1 - angka2
    elif operator == "*":
        return angka1 * angka2
    elif operator == "/":
        if angka2 == 0:
            print("❌ Tidak bisa membagi dengan nol!")
            return None
        return angka1 / angka2
    else:
        print(f"❌ Operator '{operator}' tidak dikenali.")
        return None

# Coba fungsi-nya dulu secara manual sebelum dipakai interaktif
print(hitung(10, "+", 5))
print(hitung(10, "/", 0))
print(hitung(10, "%", 5))

15
❌ Tidak bisa membagi dengan nol!
None
❌ Operator '%' tidak dikenali.
None


In [103]:
print("🧮 KALKULATOR SEDERHANA")
print("Operator yang didukung: + - * /")
print("Ketik 'keluar' pada angka pertama untuk mengakhiri program.\n")

while True:
    angka1_input = input("Masukkan angka pertama (atau 'keluar'): ")

    # Cek kondisi keluar dari loop
    if angka1_input.lower() == "keluar":
        print("\n👋 Kalkulator ditutup. Sampai jumpa!")
        break

    operator_input = input("Masukkan operator (+ - * /): ")
    angka2_input   = input("Masukkan angka kedua: ")

    # Casting input String menjadi Float agar bisa dihitung
    try:
        angka1 = float(angka1_input)
        angka2 = float(angka2_input)
    except ValueError:
        print("❌ Input angka tidak valid, coba lagi.\n")
        continue  # lewati sisa kode, ulang dari awal loop

    hasil = hitung(angka1, operator_input, angka2)

    if hasil is not None:
        print(f"✅ Hasil: {angka1} {operator_input} {angka2} = {hasil}\n")
    else:
        print()  # baris kosong saja sebagai pemisah

🧮 KALKULATOR SEDERHANA
Operator yang didukung: + - * /
Ketik 'keluar' pada angka pertama untuk mengakhiri program.

✅ Hasil: 65.0 * 78.0 = 5070.0


👋 Kalkulator ditutup. Sampai jumpa!


### **💻 Praktik 4: Fungsi Modular dengan `*args` & `**kwargs`**

Terkadang kita tidak tahu pasti berapa banyak input yang akan diterima
sebuah fungsi. Di praktik ini kita akan belajar membuat fungsi yang
fleksibel menggunakan `*args` (menampung input dalam bentuk Tuple) dan
`**kwargs` (menampung input bernama dalam bentuk Dictionary).

In [104]:
# Fungsi biasa -> hanya bisa menerima jumlah parameter yang FIXED
def jumlahkan_tiga(a, b, c):
    return a + b + c

print(f"Jumlah 3 angka: {jumlahkan_tiga(10, 20, 30)}")

# Masalahnya: bagaimana jika kita ingin menjumlahkan 5 angka? 10 angka?
# Kita tidak mungkin membuat fungsi terpisah untuk setiap kemungkinan jumlah input.

Jumlah 3 angka: 60


In [105]:
def jumlahkan_semua(*args):
    """
    *args menerima input dalam jumlah berapapun dan membungkusnya
    secara otomatis menjadi sebuah Tuple.
    """
    print(f"Tipe data args : {type(args)}")
    print(f"Isi args       : {args}")

    total = 0
    for angka in args:
        total += angka
    return total

print(f"Jumlah 3 angka  : {jumlahkan_semua(10, 20, 30)}")
print(f"Jumlah 5 angka  : {jumlahkan_semua(1, 2, 3, 4, 5)}")
print(f"Jumlah 1 angka  : {jumlahkan_semua(99)}")

Tipe data args : <class 'tuple'>
Isi args       : (10, 20, 30)
Jumlah 3 angka  : 60
Tipe data args : <class 'tuple'>
Isi args       : (1, 2, 3, 4, 5)
Jumlah 5 angka  : 15
Tipe data args : <class 'tuple'>
Isi args       : (99,)
Jumlah 1 angka  : 99


In [106]:
def buat_profil(**kwargs):
    """
    **kwargs menerima input bernama (keyword) dalam jumlah berapapun
    dan membungkusnya secara otomatis menjadi sebuah Dictionary.
    """
    print(f"Tipe data kwargs : {type(kwargs)}")
    print(f"Isi kwargs       : {kwargs}")
    print()

    print("📋 PROFIL PESERTA")
    print("-" * 25)
    for key, value in kwargs.items():
        print(f"{key.capitalize():<10} : {value}")

# Fungsi ini bisa dipanggil dengan jumlah dan nama parameter yang berbeda-beda
buat_profil(nama="Andi", umur=20, kota="Bandung")
print()
buat_profil(nama="Sari", umur=22, kota="Jakarta", hobi="Coding")

Tipe data kwargs : <class 'dict'>
Isi kwargs       : {'nama': 'Andi', 'umur': 20, 'kota': 'Bandung'}

📋 PROFIL PESERTA
-------------------------
Nama       : Andi
Umur       : 20
Kota       : Bandung

Tipe data kwargs : <class 'dict'>
Isi kwargs       : {'nama': 'Sari', 'umur': 22, 'kota': 'Jakarta', 'hobi': 'Coding'}

📋 PROFIL PESERTA
-------------------------
Nama       : Sari
Umur       : 22
Kota       : Jakarta
Hobi       : Coding


In [107]:
def buat_laporan_transaksi(nama_pembeli, *barang, **info_tambahan):
    """
    Parameter biasa  -> wajib diisi, urutannya tetap
    *barang          -> daftar barang yang dibeli (jumlah fleksibel)
    **info_tambahan  -> informasi ekstra opsional (metode bayar, diskon, dll)
    """
    print("🧾 LAPORAN TRANSAKSI")
    print("=" * 35)
    print(f"Pembeli       : {nama_pembeli}")

    print(f"Barang dibeli : {', '.join(barang)}")

    if info_tambahan:
        print("Info tambahan :")
        for key, value in info_tambahan.items():
            print(f"   - {key.capitalize()}: {value}")

    print("=" * 35)

# Contoh pemanggilan dengan kombinasi ketiga jenis parameter
buat_laporan_transaksi(
    "Budi",
    "Pulpen", "Buku", "Penghapus",
    metode_bayar="QRIS",
    diskon="10%"
)

🧾 LAPORAN TRANSAKSI
Pembeli       : Budi
Barang dibeli : Pulpen, Buku, Penghapus
Info tambahan :
   - Metode_bayar: QRIS
   - Diskon: 10%


## **📏 Sesi 3: Pengantar Library, Array, dan Matriks dengan NumPy**

### **3.1 Mengapa Kita Butuh NumPy?**

`List` bawaan Python bisa menampung berbagai tipe data sekaligus karena setiap elemennya dibungkus sebagai objek terpisah di memori. Akibatnya, proses komputasi matematika pada List menjadi sangat lambat.

**NumPy (Numerical Python)** hadir membawa solusi berupa **ND-Array**. Semua data di dalam NumPy harus bertipe sama (homogen). Karena ditulis menggunakan bahasa C di balik layar, NumPy mampu mengeksekusi kalkulasi jutaan data piksel gambar secara simultan melalui sistem **Vektorisasi** tanpa perlu menggunakan perulangan *for-loop* tradisional yang lambat.

### **3.2 Operasi Aritmatika, Shape Manipulation, & Stacking Matriks**

* **Array 1D dan Matriks 2D:** Array satu dimensi merepresentasikan baris vektor angka, sedangkan Matriks dua dimensi (Baris $\times$ Kolom) merepresentasikan grid piksel warna pada gambar digital.
* **Shape Manipulation:** Kemampuan mengubah dimensi matriks tanpa merusak datanya (misalnya mengubah array panjang $1 \times 9$ menjadi kotak $3 \times 3$ menggunakan `.reshape()`).
* **Stacking Matriks:** Teknik menggabungkan beberapa matriks menjadi satu kesatuan, baik secara vertikal (`np.vstack`) maupun horizontal (`np.hstack`). Di dunia AI, teknik ini sangat penting untuk menggabungkan beberapa fitur gambar dataset.

### **3.3 Operasi Linear Aljabar untuk Gambar**

Pada tingkat lanjut, NumPy mempermudah operasi matematika murni yang menjadi motor penggerak algoritma *Computer Vision*:

* **Perkalian `.dot()` dan `.cross()`:** Digunakan untuk kalkulasi proyeksi objek dan transformasi koordinat visual.
* **Invers Matriks:** Digunakan untuk membalikkan nilai transformasi spasial pada gambar (seperti operasi rotasi atau pencerminan balik).

### **💻 Praktik 1: Mengapa Kita Butuh NumPy?**

`List` bawaan Python bisa menampung berbagai tipe data sekaligus, tapi
itu juga yang membuatnya lambat untuk komputasi matematika berskala besar.
Di praktik ini kita akan membuktikan langsung lewat angka — seberapa jauh
perbedaan kecepatan antara List biasa dan NumPy Array saat memproses
jutaan data, berkat sistem **Vektorisasi**.

In [108]:
import numpy as np
import time

print(f"✅ NumPy berhasil diimpor, versi: {np.__version__}")

✅ NumPy berhasil diimpor, versi: 2.4.1


In [109]:
# Membuat List besar berisi 1 juta angka
jumlah_data = 1_000_000
data_list = list(range(jumlah_data))

# Mengalikan setiap elemen dengan 2 menggunakan for-loop manual
waktu_mulai = time.time()

hasil_list = []
for angka in data_list:
    hasil_list.append(angka * 2)

waktu_selesai = time.time()
durasi_list = waktu_selesai - waktu_mulai

print(f"⏱️  Waktu proses menggunakan List + for-loop : {durasi_list:.5f} detik")
print(f"Contoh hasil (5 data pertama): {hasil_list[:5]}")

⏱️  Waktu proses menggunakan List + for-loop : 0.05620 detik
Contoh hasil (5 data pertama): [0, 2, 4, 6, 8]


In [110]:
# Membuat NumPy Array dengan jumlah data yang sama
data_array = np.arange(jumlah_data)

waktu_mulai = time.time()

# Vektorisasi -> operasi diterapkan ke SELURUH elemen sekaligus, tanpa for-loop
hasil_array = data_array * 2

waktu_selesai = time.time()
durasi_array = waktu_selesai - waktu_mulai

print(f"⏱️  Waktu proses menggunakan NumPy Array (vektorisasi) : {durasi_array:.5f} detik")
print(f"Contoh hasil (5 data pertama): {hasil_array[:5]}")

⏱️  Waktu proses menggunakan NumPy Array (vektorisasi) : 0.00261 detik
Contoh hasil (5 data pertama): [0 2 4 6 8]


In [111]:
lebih_cepat = durasi_list / durasi_array if durasi_array > 0 else float("inf")

print("📊 PERBANDINGAN KECEPATAN")
print("=" * 45)
print(f"List + for-loop  : {durasi_list:.5f} detik")
print(f"NumPy Array      : {durasi_array:.5f} detik")
print(f"{'─' * 45}")
print(f"🚀 NumPy lebih cepat ±{lebih_cepat:.0f}x dibanding List biasa")
print("=" * 45)
print()
print("💡 Inilah alasan NumPy menjadi fondasi wajib di dunia AI & Computer Vision —")
print("   gambar terdiri dari jutaan piksel yang harus diproses secara bersamaan.")

📊 PERBANDINGAN KECEPATAN
List + for-loop  : 0.05620 detik
NumPy Array      : 0.00261 detik
─────────────────────────────────────────────
🚀 NumPy lebih cepat ±21x dibanding List biasa

💡 Inilah alasan NumPy menjadi fondasi wajib di dunia AI & Computer Vision —
   gambar terdiri dari jutaan piksel yang harus diproses secara bersamaan.


In [112]:
# List bawaan Python boleh menampung tipe data berbeda dalam satu koleksi
list_campur = [1, "dua", 3.0, True]
print(f"List campur tipe data -> {list_campur}")
for item in list_campur:
    print(f"   {item} -> tipe: {type(item)}")

print()

# NumPy Array akan otomatis menyamakan (memaksa) semua elemen menjadi satu tipe
array_dipaksa = np.array([1, "dua", 3.0, True])
print(f"NumPy Array hasil konversi -> {array_dipaksa}")
print(f"Tipe data seluruh elemen dipaksa jadi -> {array_dipaksa.dtype}")

List campur tipe data -> [1, 'dua', 3.0, True]
   1 -> tipe: <class 'int'>
   dua -> tipe: <class 'str'>
   3.0 -> tipe: <class 'float'>
   True -> tipe: <class 'bool'>

NumPy Array hasil konversi -> ['1' 'dua' '3.0' 'True']
Tipe data seluruh elemen dipaksa jadi -> <U32


### **💻 Praktik 2: Array 1D, Matriks 2D, & Operasi Aritmatika**

Sekarang kita masuk ke bentuk data yang sebenarnya dipakai di dunia
Computer Vision — Array satu dimensi (vektor angka) dan Matriks dua
dimensi (grid baris × kolom, persis seperti susunan piksel pada gambar).
Kita juga akan mencoba operasi aritmatika yang berjalan otomatis ke
seluruh elemen sekaligus.

In [113]:
# Array 1D -> merepresentasikan vektor baris angka
array_1d = np.array([10, 20, 30, 40, 50])

print(f"Array 1D       : {array_1d}")
print(f"Dimensi (ndim) : {array_1d.ndim}")
print(f"Bentuk (shape) : {array_1d.shape}")
print(f"Jumlah elemen  : {array_1d.size}")
print(f"Tipe data      : {array_1d.dtype}")

Array 1D       : [10 20 30 40 50]
Dimensi (ndim) : 1
Bentuk (shape) : (5,)
Jumlah elemen  : 5
Tipe data      : int64


In [114]:
# Matriks 2D -> Baris x Kolom, persis seperti grid piksel gambar digital
matriks_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matriks 2D:")
print(matriks_2d)
print()
print(f"Dimensi (ndim) : {matriks_2d.ndim}")
print(f"Bentuk (shape) : {matriks_2d.shape}  -> artinya {matriks_2d.shape[0]} baris, {matriks_2d.shape[1]} kolom")
print(f"Jumlah elemen  : {matriks_2d.size}")

Matriks 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimensi (ndim) : 2
Bentuk (shape) : (3, 3)  -> artinya 3 baris, 3 kolom
Jumlah elemen  : 9


In [115]:
# Format akses: matriks[baris, kolom]
print(f"Elemen baris ke-0, kolom ke-1 -> {matriks_2d[0, 1]}")
print(f"Seluruh baris ke-1            -> {matriks_2d[1, :]}")
print(f"Seluruh kolom ke-2             -> {matriks_2d[:, 2]}")
print(f"Sub-matriks 2x2 pojok kiri atas:\n{matriks_2d[0:2, 0:2]}")

Elemen baris ke-0, kolom ke-1 -> 2
Seluruh baris ke-1            -> [4 5 6]
Seluruh kolom ke-2             -> [3 6 9]
Sub-matriks 2x2 pojok kiri atas:
[[1 2]
 [4 5]]


In [116]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([10, 20, 30, 40])

print(f"array_a         : {array_a}")
print(f"array_b         : {array_b}")
print("=" * 30)
print(f"Penjumlahan     : {array_a + array_b}")
print(f"Pengurangan     : {array_b - array_a}")
print(f"Perkalian       : {array_a * array_b}   (element-wise, BUKAN perkalian matriks)")
print(f"Pembagian       : {array_b / array_a}")
print(f"Pangkat         : {array_a ** 2}")

array_a         : [1 2 3 4]
array_b         : [10 20 30 40]
Penjumlahan     : [11 22 33 44]
Pengurangan     : [ 9 18 27 36]
Perkalian       : [ 10  40  90 160]   (element-wise, BUKAN perkalian matriks)
Pembagian       : [10. 10. 10. 10.]
Pangkat         : [ 1  4  9 16]


In [117]:
# Bayangkan matriks ini adalah representasi nilai piksel grayscale sederhana
gambar_asli = np.array([
    [100, 150, 200],
    [50,  80,  120],
    [30,  60,  90]
])

print("Matriks 'gambar' asli (nilai piksel):")
print(gambar_asli)

# Menambah brightness -> tambahkan angka ke SELURUH piksel sekaligus
gambar_lebih_terang = gambar_asli + 50
print("\nSetelah ditambah brightness +50:")
print(gambar_lebih_terang)

# Mengurangi brightness sekaligus membatasi nilai maksimal piksel (0-255)
gambar_redup = np.clip(gambar_asli - 70, 0, 255)
print("\nSetelah dikurangi brightness -70 (dengan clipping 0-255):")
print(gambar_redup)

Matriks 'gambar' asli (nilai piksel):
[[100 150 200]
 [ 50  80 120]
 [ 30  60  90]]

Setelah ditambah brightness +50:
[[150 200 250]
 [100 130 170]
 [ 80 110 140]]

Setelah dikurangi brightness -70 (dengan clipping 0-255):
[[ 30  80 130]
 [  0  10  50]
 [  0   0  20]]


### **💻 Praktik 3: Shape Manipulation (`reshape`) & Stacking Matriks**

Kadang kita perlu mengubah bentuk (dimensi) sebuah Array tanpa merusak
datanya — misalnya mengubah Array panjang menjadi bentuk kotak. Kita juga
akan belajar menggabungkan beberapa Matriks menjadi satu kesatuan, sebuah
teknik yang sangat penting saat menggabungkan beberapa fitur dataset gambar.

In [118]:
# Array 1D berisi 9 angka berurutan
array_panjang = np.arange(1, 10)
print(f"Array asli (1D)    : {array_panjang}")
print(f"Shape asli         : {array_panjang.shape}")

# Ubah menjadi Matriks 3x3 menggunakan reshape()
matriks_3x3 = array_panjang.reshape(3, 3)
print(f"\nSetelah reshape(3, 3):")
print(matriks_3x3)
print(f"Shape baru         : {matriks_3x3.shape}")

Array asli (1D)    : [1 2 3 4 5 6 7 8 9]
Shape asli         : (9,)

Setelah reshape(3, 3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape baru         : (3, 3)


In [119]:
# Coba reshape ke ukuran yang TIDAK sesuai jumlah elemennya -> akan error
array_contoh = np.arange(1, 9)  # totalnya 8 elemen
print(f"Array dengan {array_contoh.size} elemen: {array_contoh}")

try:
    hasil_gagal = array_contoh.reshape(3, 3)  # 3x3 = 9, tapi datanya cuma 8
except ValueError as e:
    print(f"\n❌ Gagal reshape! Error: {e}")
    print("   Penyebab: 3 baris x 3 kolom = 9 slot, tapi data yang tersedia hanya 8.")

# Reshape yang benar untuk 8 elemen
hasil_benar = array_contoh.reshape(2, 4)
print(f"\n✅ Reshape ke (2, 4) berhasil:")
print(hasil_benar)

Array dengan 8 elemen: [1 2 3 4 5 6 7 8]

❌ Gagal reshape! Error: cannot reshape array of size 8 into shape (3,3)
   Penyebab: 3 baris x 3 kolom = 9 slot, tapi data yang tersedia hanya 8.

✅ Reshape ke (2, 4) berhasil:
[[1 2 3 4]
 [5 6 7 8]]


In [120]:
matriks_asal = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matriks asal (2D):")
print(matriks_asal)

array_flatten = matriks_asal.flatten()
print(f"\nSetelah flatten() menjadi 1D: {array_flatten}")
print("\n💡 flatten() sering dipakai sebelum gambar dimasukkan ke model AI")
print("   yang membutuhkan input berbentuk vektor 1D.")

Matriks asal (2D):
[[1 2 3]
 [4 5 6]]

Setelah flatten() menjadi 1D: [1 2 3 4 5 6]

💡 flatten() sering dipakai sebelum gambar dimasukkan ke model AI
   yang membutuhkan input berbentuk vektor 1D.


In [121]:
matriks_a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matriks_b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matriks A:")
print(matriks_a)
print("\nMatriks B:")
print(matriks_b)

# vstack -> menumpuk matriks B di BAWAH matriks A (menambah jumlah baris)
hasil_vstack = np.vstack((matriks_a, matriks_b))
print(f"\nHasil vstack (gabung vertikal), shape: {hasil_vstack.shape}")
print(hasil_vstack)

Matriks A:
[[1 2 3]
 [4 5 6]]

Matriks B:
[[ 7  8  9]
 [10 11 12]]

Hasil vstack (gabung vertikal), shape: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [122]:
# hstack -> menempelkan matriks B di SAMPING matriks A (menambah jumlah kolom)
hasil_hstack = np.hstack((matriks_a, matriks_b))
print(f"Hasil hstack (gabung horizontal), shape: {hasil_hstack.shape}")
print(hasil_hstack)

print("\n💡 Di Computer Vision, vstack/hstack sering dipakai untuk menggabungkan")
print("   beberapa channel warna (Red, Green, Blue) menjadi satu gambar utuh,")
print("   atau menggabungkan beberapa fitur dataset menjadi satu tabel besar.")

Hasil hstack (gabung horizontal), shape: (2, 6)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

💡 Di Computer Vision, vstack/hstack sering dipakai untuk menggabungkan
   beberapa channel warna (Red, Green, Blue) menjadi satu gambar utuh,
   atau menggabungkan beberapa fitur dataset menjadi satu tabel besar.


### **💻 Praktik 4: Operasi Linear Aljabar untuk Gambar (Dot, Cross, Invers)**

Operasi-operasi ini adalah motor penggerak di balik algoritma Computer
Vision — mulai dari transformasi koordinat, proyeksi objek, hingga
membalikkan kembali sebuah transformasi spasial pada gambar.

In [123]:
matriks_a = np.array([
    [1, 2],
    [3, 4]
])

matriks_b = np.array([
    [5, 6],
    [7, 8]
])

print("Matriks A:")
print(matriks_a)
print("\nMatriks B:")
print(matriks_b)

# Perkalian element-wise BIASA (bukan perkalian matriks sebenarnya)
print("\nA * B (element-wise, posisi sejajar dikalikan langsung):")
print(matriks_a * matriks_b)

# Perkalian matriks SEBENARNYA menggunakan .dot()
print("\nA.dot(B) (perkalian matriks / dot product):")
print(matriks_a.dot(matriks_b))

Matriks A:
[[1 2]
 [3 4]]

Matriks B:
[[5 6]
 [7 8]]

A * B (element-wise, posisi sejajar dikalikan langsung):
[[ 5 12]
 [21 32]]

A.dot(B) (perkalian matriks / dot product):
[[19 22]
 [43 50]]


In [124]:
# Bayangkan ini adalah satu titik koordinat (x, y) pada sebuah gambar
titik_koordinat = np.array([4, 3])

# Matriks transformasi untuk memperbesar gambar 2x (scaling)
matriks_scaling = np.array([
    [2, 0],
    [0, 2]
])

titik_baru = matriks_scaling.dot(titik_koordinat)

print(f"Koordinat asli         : {titik_koordinat}")
print(f"Matriks transformasi (scaling 2x):")
print(matriks_scaling)
print(f"\nKoordinat setelah transformasi : {titik_baru}")
print("\n💡 Inilah dasar bagaimana AI memperbesar, memutar, atau memindahkan")
print("   posisi objek pada sebuah gambar secara matematis.")

Koordinat asli         : [4 3]
Matriks transformasi (scaling 2x):
[[2 0]
 [0 2]]

Koordinat setelah transformasi : [8 6]

💡 Inilah dasar bagaimana AI memperbesar, memutar, atau memindahkan
   posisi objek pada sebuah gambar secara matematis.


In [125]:
# Cross product hanya berlaku pada vektor 3D, sering dipakai untuk
# menghitung arah normal (tegak lurus) pada permukaan objek 3D
vektor_a = np.array([1, 0, 0])
vektor_b = np.array([0, 1, 0])

hasil_cross = np.cross(vektor_a, vektor_b)

print(f"Vektor A          : {vektor_a}")
print(f"Vektor B          : {vektor_b}")
print(f"Cross Product A×B : {hasil_cross}")
print("\n💡 Cross product menghasilkan vektor baru yang tegak lurus terhadap")
print("   kedua vektor asalnya — dipakai untuk menghitung arah normal permukaan")
print("   pada rendering objek 3D.")

Vektor A          : [1 0 0]
Vektor B          : [0 1 0]
Cross Product A×B : [0 0 1]

💡 Cross product menghasilkan vektor baru yang tegak lurus terhadap
   kedua vektor asalnya — dipakai untuk menghitung arah normal permukaan
   pada rendering objek 3D.


In [126]:
# Matriks transformasi scaling 2x dari contoh sebelumnya
matriks_scaling = np.array([
    [2, 0],
    [0, 2]
])

# Hitung invers-nya menggunakan np.linalg.inv()
matriks_invers = np.linalg.inv(matriks_scaling)

print("Matriks transformasi asli (scaling 2x):")
print(matriks_scaling)
print("\nMatriks invers (untuk membalikkan transformasi):")
print(matriks_invers)

# Buktikan: titik yang sudah ditransformasi, dikalikan invers, akan KEMBALI ke asal
titik_asli           = np.array([4, 3])
titik_setelah_scaling = matriks_scaling.dot(titik_asli)
titik_kembali_normal  = matriks_invers.dot(titik_setelah_scaling)

print(f"\nTitik koordinat asli         : {titik_asli}")
print(f"Setelah di-scaling 2x        : {titik_setelah_scaling}")
print(f"Setelah dikembalikan (invers): {titik_kembali_normal}")
print("\n💡 Invers matriks dipakai untuk membalikkan transformasi spasial,")
print("   misalnya mengembalikan gambar yang sudah diputar atau dicerminkan ke posisi semula.")

Matriks transformasi asli (scaling 2x):
[[2 0]
 [0 2]]

Matriks invers (untuk membalikkan transformasi):
[[0.5 0. ]
 [0.  0.5]]

Titik koordinat asli         : [4 3]
Setelah di-scaling 2x        : [8 6]
Setelah dikembalikan (invers): [4. 3.]

💡 Invers matriks dipakai untuk membalikkan transformasi spasial,
   misalnya mengembalikan gambar yang sudah diputar atau dicerminkan ke posisi semula.


In [127]:
# Tidak semua matriks punya invers -- matriks "singular" tidak bisa dibalik
matriks_singular = np.array([
    [2, 4],
    [1, 2]
])

print("Matriks singular (tidak memiliki invers):")
print(matriks_singular)

try:
    invers_gagal = np.linalg.inv(matriks_singular)
except np.linalg.LinAlgError as e:
    print(f"\n❌ Gagal menghitung invers! Error: {e}")
    print("   Penyebab: determinan matriks ini bernilai 0 (Singular Matrix),")
    print("   sehingga transformasinya tidak bisa dibalik secara matematis.")

Matriks singular (tidak memiliki invers):
[[2 4]
 [1 2]]

❌ Gagal menghitung invers! Error: Singular matrix
   Penyebab: determinan matriks ini bernilai 0 (Singular Matrix),
   sehingga transformasinya tidak bisa dibalik secara matematis.


## **🗑️ Sesi 4: Pengantar OOP (Object-Oriented Programming) & Mini Project**

### **4.1 Pilar Utama OOP: Class, Object, dan Variabel Instance**

*Object-Oriented Programming* (OOP) membantu kita mengorganisasi kode kompleks dengan memodelkannya seperti objek di dunia nyata.

* **`Class`:** Cetakan blueprint/rancangan dasar.
* **`Object`:** Produk nyata yang berhasil dibuat dari cetakan tersebut.
* **`__init__()` (Constructor):** Method khusus yang otomatis berjalan pertama kali saat objek diciptakan untuk menginisialisasi nilai awal dari **Instance Variables** (atribut unik milik objek tersebut).

### **4.2 Proteksi Data: Enkapsulasi, Private Variables, dan Getter-Setter**

Agar variabel penting di dalam objek tidak bisa diubah sembarangan dari luar, kita menerapkan prinsip **Enkapsulasi**:

* **Private Variables:** Ditandai dengan tanda *double underscore* (misal: `self.__harga`). Variabel ini tersembunyi dan tidak bisa diakses langsung dari luar class.
* **Getter & Setter:** Method khusus menggunakan dekorator `@property` untuk mengambil (*get*) dan mengubah (*set*) nilai variabel privat secara aman lewat validasi internal logika kode.

### **4.3 Pewarisan Sifat: Inheritance & Diamond Problem**

* **Inheritance (Pewarisan):** Class baru (*Child Class*) bisa mewarisi seluruh fungsi dan atribut dari class induknya (*Parent Class*), sehingga kita tidak perlu menulis ulang kode yang sama. Kita bisa memanggil fungsi induk menggunakan keyword `super()`.
* **Diamond Problem & MRO:** Ketika sebuah class menerima pewarisan dari dua induk yang berbeda (*Multiple Inheritance*), Python menggunakan aturan **Method Resolution Order (MRO)** untuk menentukan urutan induk mana yang harus dieksekusi terlebih dahulu agar tidak terjadi konflik logika.

### **4.4 Magic Methods & Abstract Class**

* **Magic Methods:** Method bawaan Python yang diawali dan diakhiri *double underscore* (seperti `__str__` atau `__repr__`). Kita bisa memodifikasi method ini agar objek buatan kita bisa merespons perintah bawaan Python seperti print() atau operasi matematika `+`.
* **Abstract Class:** Class suci yang tidak bisa dicetak langsung menjadi objek. Class ini hanya berfungsi sebagai "kontrak cetak biru induk" yang memaksa semua class anak untuk wajib mengimplementasikan fungsi-fungsi tertentu.

### **💻 Praktik 1: Class, Object, & `__init__` (Constructor)**

*Object-Oriented Programming* membantu kita mengorganisasi kode kompleks
dengan memodelkannya seperti objek di dunia nyata. Di praktik ini kita
akan membuat `Class` sebagai cetakan (blueprint), lalu mencetak `Object`
nyata dari cetakan tersebut menggunakan `__init__()`.

In [128]:
class Mahasiswa:
    """
    Class adalah cetakan/blueprint -- belum berupa data nyata,
    hanya rancangan atribut dan perilaku apa saja yang akan dimiliki Object.
    """

    def __init__(self, nama, umur, jurusan):
        """
        __init__() otomatis berjalan pertama kali saat Object dibuat.
        self merujuk ke Object itu sendiri, agar setiap Object punya
        nilai atribut yang independen satu sama lain.
        """
        self.nama = nama
        self.umur = umur
        self.jurusan = jurusan
        print(f"✅ Object Mahasiswa '{self.nama}' berhasil dibuat.")

# Mencetak Object NYATA dari Class Mahasiswa -- proses ini disebut instansiasi
mhs1 = Mahasiswa("Andi", 20, "Teknik Informatika")
mhs2 = Mahasiswa("Sari", 22, "Sistem Informasi")

print(f"\nNama mhs1    : {mhs1.nama}")
print(f"Jurusan mhs1 : {mhs1.jurusan}")
print(f"Nama mhs2    : {mhs2.nama}")
print(f"Jurusan mhs2 : {mhs2.jurusan}")

✅ Object Mahasiswa 'Andi' berhasil dibuat.
✅ Object Mahasiswa 'Sari' berhasil dibuat.

Nama mhs1    : Andi
Jurusan mhs1 : Teknik Informatika
Nama mhs2    : Sari
Jurusan mhs2 : Sistem Informasi


In [129]:
# Buktikan bahwa mhs1 dan mhs2 adalah Object TERPISAH dengan data masing-masing
mhs1.umur = 21  # ulang tahun, umur mhs1 berubah

print(f"Umur mhs1 setelah diubah : {mhs1.umur}")
print(f"Umur mhs2 (tidak terpengaruh) : {mhs2.umur}")

print(f"\nmhs1 is mhs2 -> {mhs1 is mhs2}   (dua Object yang berbeda di memori)")

Umur mhs1 setelah diubah : 21
Umur mhs2 (tidak terpengaruh) : 22

mhs1 is mhs2 -> False   (dua Object yang berbeda di memori)


In [130]:
class Mahasiswa:
    def __init__(self, nama, umur, jurusan):
        self.nama = nama
        self.umur = umur
        self.jurusan = jurusan
        self.daftar_nilai = []  # setiap Object punya daftar nilai sendiri

    def tambah_nilai(self, nilai):
        """Method -> fungsi yang berada DI DALAM Class, mewakili perilaku Object."""
        self.daftar_nilai.append(nilai)
        print(f"📝 Nilai {nilai} ditambahkan untuk {self.nama}.")

    def hitung_rata_rata(self):
        if len(self.daftar_nilai) == 0:
            return 0
        return sum(self.daftar_nilai) / len(self.daftar_nilai)

# Membuat Object & menggunakan Method-nya
mhs1 = Mahasiswa("Andi", 20, "Teknik Informatika")
mhs1.tambah_nilai(85)
mhs1.tambah_nilai(90)
mhs1.tambah_nilai(78)

print(f"\nDaftar nilai {mhs1.nama} : {mhs1.daftar_nilai}")
print(f"Rata-rata nilai          : {mhs1.hitung_rata_rata():.2f}")

📝 Nilai 85 ditambahkan untuk Andi.
📝 Nilai 90 ditambahkan untuk Andi.
📝 Nilai 78 ditambahkan untuk Andi.

Daftar nilai Andi : [85, 90, 78]
Rata-rata nilai          : 84.33


### **💻 Praktik 2: Enkapsulasi — Private Variables & Getter-Setter**

Agar variabel penting di dalam Object tidak bisa diubah sembarangan dari
luar, kita menerapkan **Enkapsulasi**. Di praktik ini kita akan membuat
variabel privat menggunakan *double underscore* (`__`), lalu menyediakan
akses yang aman lewat **Getter** dan **Setter** menggunakan dekorator `@property`.

In [131]:
class RekeningBankTidakAman:
    def __init__(self, pemilik, saldo_awal):
        self.pemilik = pemilik
        self.saldo = saldo_awal  # variabel PUBLIC, bisa diubah siapa saja

rekening = RekeningBankTidakAman("Andi", 500_000)
print(f"Saldo awal {rekening.pemilik} : Rp{rekening.saldo:,}")

# Karena variabelnya PUBLIC, siapapun bisa mengubahnya secara sembarangan
rekening.saldo = -999_999_999  # tidak ada validasi apapun!
print(f"Saldo setelah diubah langsung dari luar : Rp{rekening.saldo:,}")
print("\n⚠️  Ini berbahaya -- saldo bisa diubah jadi nilai tidak logis tanpa validasi apapun.")

Saldo awal Andi : Rp500,000
Saldo setelah diubah langsung dari luar : Rp-999,999,999

⚠️  Ini berbahaya -- saldo bisa diubah jadi nilai tidak logis tanpa validasi apapun.


In [132]:
class RekeningBank:
    def __init__(self, pemilik, saldo_awal):
        self.pemilik = pemilik
        self.__saldo = saldo_awal  # tanda __ membuat variabel ini PRIVATE

rekening = RekeningBank("Andi", 500_000)

try:
    print(rekening.__saldo)  # mencoba akses langsung dari luar Class
except AttributeError as e:
    print(f"❌ Gagal diakses langsung! Error: {e}")
    print("   Penyebab: __saldo adalah variabel privat, tersembunyi dari luar Class.")

❌ Gagal diakses langsung! Error: 'RekeningBank' object has no attribute '__saldo'
   Penyebab: __saldo adalah variabel privat, tersembunyi dari luar Class.


In [133]:
class RekeningBank:
    def __init__(self, pemilik, saldo_awal):
        self.pemilik = pemilik
        self.__saldo = saldo_awal

    @property
    def saldo(self):
        """Getter -- cara AMAN untuk MEMBACA nilai variabel privat."""
        return self.__saldo

    @saldo.setter
    def saldo(self, nilai_baru):
        """Setter -- cara AMAN untuk MENGUBAH nilai variabel privat, dengan validasi."""
        if nilai_baru < 0:
            print("❌ Saldo tidak boleh bernilai negatif! Perubahan ditolak.")
            return
        self.__saldo = nilai_baru
        print(f"✅ Saldo berhasil diperbarui menjadi Rp{self.__saldo:,}")

rekening = RekeningBank("Andi", 500_000)

# Mengakses nilai lewat Getter (terlihat seperti atribut biasa, tapi sebenarnya method)
print(f"Saldo saat ini : Rp{rekening.saldo:,}")

# Mengubah nilai lewat Setter -- otomatis tervalidasi
rekening.saldo = 750_000
print(f"Saldo terbaru  : Rp{rekening.saldo:,}")

# Coba ubah ke nilai negatif -- akan ditolak oleh validasi Setter
rekening.saldo = -100_000
print(f"Saldo tetap    : Rp{rekening.saldo:,}")

Saldo saat ini : Rp500,000
✅ Saldo berhasil diperbarui menjadi Rp750,000
Saldo terbaru  : Rp750,000
❌ Saldo tidak boleh bernilai negatif! Perubahan ditolak.
Saldo tetap    : Rp750,000


In [134]:
class RekeningBank:
    def __init__(self, pemilik, saldo_awal):
        self.pemilik = pemilik
        self.__saldo = saldo_awal

    @property
    def saldo(self):
        return self.__saldo

    def deposit(self, jumlah):
        if jumlah <= 0:
            print("❌ Jumlah deposit harus lebih dari 0.")
            return
        self.__saldo += jumlah
        print(f"💰 Deposit Rp{jumlah:,} berhasil. Saldo sekarang: Rp{self.__saldo:,}")

    def tarik_tunai(self, jumlah):
        if jumlah > self.__saldo:
            print(f"❌ Saldo tidak cukup! Saldo tersedia: Rp{self.__saldo:,}")
            return
        self.__saldo -= jumlah
        print(f"💸 Penarikan Rp{jumlah:,} berhasil. Saldo sekarang: Rp{self.__saldo:,}")

rekening = RekeningBank("Sari", 1_000_000)
rekening.deposit(500_000)
rekening.tarik_tunai(2_000_000)  # akan ditolak, saldo tidak cukup
rekening.tarik_tunai(300_000)

💰 Deposit Rp500,000 berhasil. Saldo sekarang: Rp1,500,000
❌ Saldo tidak cukup! Saldo tersedia: Rp1,500,000
💸 Penarikan Rp300,000 berhasil. Saldo sekarang: Rp1,200,000


### **💻 Praktik 3: Inheritance, `super()`, & Method Resolution Order (MRO)**

`Inheritance` (pewarisan) memungkinkan sebuah Class baru (*Child Class*)
mewarisi seluruh atribut dan method dari Class induknya (*Parent Class*),
sehingga kita tidak perlu menulis ulang kode yang sama. Kita juga akan
melihat bagaimana Python menentukan urutan eksekusi saat sebuah Class
mewarisi dari lebih dari satu induk (*Multiple Inheritance*).

In [135]:
class Hewan:
    """Parent Class -- berisi atribut dan method umum yang dimiliki semua hewan."""

    def __init__(self, nama, suara):
        self.nama = nama
        self.suara = suara

    def bersuara(self):
        print(f"{self.nama} bersuara: {self.suara}!")

    def info(self):
        print(f"Ini adalah {self.nama}, sejenis hewan.")


class Kucing(Hewan):
    """Child Class -- otomatis mewarisi __init__, bersuara(), dan info() dari Hewan."""
    pass


class Anjing(Hewan):
    pass

# Kedua Child Class ini langsung bisa pakai method dari Parent Class
kucing = Kucing("Kitty", "Meong")
anjing = Anjing("Brownie", "Guk")

kucing.bersuara()
kucing.info()

anjing.bersuara()
anjing.info()

Kitty bersuara: Meong!
Ini adalah Kitty, sejenis hewan.
Brownie bersuara: Guk!
Ini adalah Brownie, sejenis hewan.


In [136]:
class Kucing(Hewan):
    def __init__(self, nama, warna_bulu):
        # super() memanggil __init__ milik Parent Class (Hewan)
        # agar kita tidak perlu menulis ulang logika nama & suara dari awal
        super().__init__(nama, suara="Meong")
        self.warna_bulu = warna_bulu  # atribut TAMBAHAN khusus milik Kucing

    def info(self):
        """Override -- menimpa method info() milik Parent dengan versi baru."""
        super().info()  # tetap panggil versi Parent dulu sebagai dasar
        print(f"Warna bulunya {self.warna_bulu}.")

kucing = Kucing("Kitty", "Oren")
kucing.bersuara()  # method ini TIDAK di-override, tetap pakai milik Parent
kucing.info()      # method ini SUDAH di-override, perilakunya berubah

Kitty bersuara: Meong!
Ini adalah Kitty, sejenis hewan.
Warna bulunya Oren.


In [137]:
class Karyawan:
    def bekerja(self):
        print("Sedang menjalankan tugas kantor.")


class Mahasiswa:
    def belajar(self):
        print("Sedang mengerjakan tugas kuliah.")


class KaryawanSambilKuliah(Karyawan, Mahasiswa):
    """Multiple Inheritance -- mewarisi dari DUA Parent Class sekaligus."""
    pass

orang = KaryawanSambilKuliah()
orang.bekerja()   # method dari Karyawan
orang.belajar()   # method dari Mahasiswa

Sedang menjalankan tugas kantor.
Sedang mengerjakan tugas kuliah.


In [138]:
class A:
    def info(self):
        print("Method info() milik Class A")

class B(A):
    def info(self):
        print("Method info() milik Class B")

class C(A):
    def info(self):
        print("Method info() milik Class C")

class D(B, C):
    """D mewarisi dari B dan C, yang keduanya juga mewarisi dari A -- inilah Diamond Problem."""
    pass

objek_d = D()
objek_d.info()  # method mana yang dijalankan? cek urutan MRO di bawah

# __mro__ menunjukkan urutan pencarian method dari kiri ke kanan
print("\nUrutan MRO Class D:")
for index, kelas in enumerate(D.__mro__, start=1):
    print(f"{index}. {kelas.__name__}")

print("\n💡 Python mencari method secara berurutan sesuai MRO: D -> B -> C -> A -> object")
print("   Itulah mengapa info() yang dijalankan adalah milik Class B, bukan C.")

Method info() milik Class B

Urutan MRO Class D:
1. D
2. B
3. C
4. A
5. object

💡 Python mencari method secara berurutan sesuai MRO: D -> B -> C -> A -> object
   Itulah mengapa info() yang dijalankan adalah milik Class B, bukan C.


### **💻 Praktik 4: Magic Methods & Abstract Class**

`Magic Methods` adalah method bawaan Python yang diawali dan diakhiri
*double underscore* (seperti `__str__` atau `__add__`). Dengan
memodifikasinya, Object buatan kita bisa merespons perintah bawaan Python
seperti `print()` atau operator matematika `+`. Kita juga akan mengenal
`Abstract Class` — cetakan induk yang tidak bisa dicetak langsung menjadi
Object, dan memaksa semua Class anak untuk mengimplementasikan fungsi tertentu.

In [139]:
class Produk:
    def __init__(self, nama, harga):
        self.nama = nama
        self.harga = harga

produk1 = Produk("Pulpen", 3000)

# Tanpa __str__, print() pada Object hanya menampilkan info memori yang tidak berguna
print(produk1)
print("\n⚠️  Outputnya tidak informatif sama sekali untuk pengguna.")


⚠️  Outputnya tidak informatif sama sekali untuk pengguna.


In [140]:
class Produk:
    def __init__(self, nama, harga):
        self.nama = nama
        self.harga = harga

    def __str__(self):
        """Dipanggil otomatis saat Object di-print() -- representasi untuk manusia."""
        return f"Produk: {self.nama} (Rp{self.harga:,})"

    def __repr__(self):
        """Representasi teknis, biasanya untuk debugging di console."""
        return f"Produk(nama='{self.nama}', harga={self.harga})"

produk1 = Produk("Pulpen", 3000)

print(produk1)          # otomatis memanggil __str__
print(repr(produk1))    # otomatis memanggil __repr__

Produk: Pulpen (Rp3,000)
Produk(nama='Pulpen', harga=3000)


In [141]:
class Produk:
    def __init__(self, nama, harga):
        self.nama = nama
        self.harga = harga

    def __str__(self):
        return f"{self.nama} (Rp{self.harga:,})"

    def __add__(self, lainnya):
        """Memodifikasi perilaku operator '+' antar dua Object Produk."""
        total_harga = self.harga + lainnya.harga
        return f"Total harga {self.nama} + {lainnya.nama} = Rp{total_harga:,}"

    def __eq__(self, lainnya):
        """Memodifikasi perilaku operator '==' -- bandingkan berdasarkan harga."""
        return self.harga == lainnya.harga

    def __lt__(self, lainnya):
        """Memodifikasi perilaku operator '<' -- untuk keperluan sorting."""
        return self.harga < lainnya.harga

pulpen  = Produk("Pulpen", 3000)
pensil  = Produk("Pensil", 3000)
penghapus = Produk("Penghapus", 2000)

print(pulpen + pensil)               # memanggil __add__
print(f"pulpen == pensil -> {pulpen == pensil}")     # memanggil __eq__
print(f"penghapus < pulpen -> {penghapus < pulpen}") # memanggil __lt__

# Karena __lt__ sudah didefinisikan, sorted() otomatis bisa dipakai!
daftar_produk = [pulpen, pensil, penghapus]
daftar_terurut = sorted(daftar_produk)
print("\nDaftar produk terurut dari harga termurah:")
for produk in daftar_terurut:
    print(f"- {produk}")

Total harga Pulpen + Pensil = Rp6,000
pulpen == pensil -> True
penghapus < pulpen -> True

Daftar produk terurut dari harga termurah:
- Penghapus (Rp2,000)
- Pulpen (Rp3,000)
- Pensil (Rp3,000)


In [142]:
from abc import ABC, abstractmethod

class BentukGeometri(ABC):
    """
    Abstract Class -- class suci ini TIDAK BISA dicetak langsung menjadi Object.
    Hanya berfungsi sebagai kontrak cetak biru bagi seluruh Class anak.
    """

    @abstractmethod
    def hitung_luas(self):
        """Setiap Child Class WAJIB mengimplementasikan method ini sendiri."""
        pass

# Coba cetak Object langsung dari Abstract Class -> akan error
try:
    bentuk = BentukGeometri()
except TypeError as e:
    print(f"❌ Gagal membuat Object! Error: {e}")
    print("   Penyebab: BentukGeometri adalah Abstract Class, tidak bisa diinstansiasi langsung.")

❌ Gagal membuat Object! Error: Can't instantiate abstract class BentukGeometri without an implementation for abstract method 'hitung_luas'
   Penyebab: BentukGeometri adalah Abstract Class, tidak bisa diinstansiasi langsung.


In [143]:
class Persegi(BentukGeometri):
    def __init__(self, sisi):
        self.sisi = sisi

    def hitung_luas(self):
        """WAJIB diimplementasikan, karena ini abstractmethod dari Parent."""
        return self.sisi ** 2


class Lingkaran(BentukGeometri):
    def __init__(self, radius):
        self.radius = radius

    def hitung_luas(self):
        return 3.14 * (self.radius ** 2)

persegi = Persegi(5)
lingkaran = Lingkaran(3)

print(f"Luas Persegi (sisi=5)    : {persegi.hitung_luas()}")
print(f"Luas Lingkaran (radius=3): {lingkaran.hitung_luas():.2f}")

print("\n💡 Abstract Class memaksa setiap Child Class untuk punya method hitung_luas(),")
print("   tapi cara perhitungannya bisa berbeda-beda sesuai bentuk masing-masing.")

Luas Persegi (sisi=5)    : 25
Luas Lingkaran (radius=3): 28.26

💡 Abstract Class memaksa setiap Child Class untuk punya method hitung_luas(),
   tapi cara perhitungannya bisa berbeda-beda sesuai bentuk masing-masing.


### **🛠️ MINI PROJECT AKHIR: Aplikasi Inventaris Toko & Kasir Mandiri**

Sebagai pembuktian kompetensi, Anda ditantang untuk membangun sebuah program aplikasi kasir interaktif berbasis objek (OOP).

**Arsitektur Program yang Wajib Diterapkan:**

1. Gunakan paradigma **OOP** dengan membuat `Class Produk` (menggunakan konsep *Private Variable* untuk harga barang) dan `Class Kasir`.
2. Integrasikan data katalog barang menggunakan struktur **Dictionary**.
3. Gunakan mekanisme kontrol perulangan `while True` agar kasir bisa terus menerima input pesanan pengguna secara interaktif lewat fungsi `input()`.
4. Terapkan sistem proteksi error menggunakan blok **Try-Except** untuk mengantisipasi jika pengguna salah memasukkan input angka atau memilih menu yang tidak terdaftar di database katalog agar program tidak langsung *crash*.

### **💻 Praktik 5 (Mini Project): Kasir Toko & Inventaris Mandiri**

Di Mini Project ini kita akan menggabungkan **seluruh konsep OOP** yang
sudah dipelajari — Class, Enkapsulasi, Inheritance, dan Magic Methods —
menjadi sebuah aplikasi kasir toko yang interaktif dan fungsional.

Arsitektur aplikasi:
- `Produk` → Class dasar yang merepresentasikan satu item barang
- `Inventaris` → Class yang mengelola keseluruhan stok barang
- `KasirToko` → Child Class dari Inventaris, menangani transaksi belanja

In [144]:
class Produk:
    def __init__(self, kode, nama, harga, stok):
        self.kode  = kode
        self.nama  = nama
        self.__harga = harga   # Private -- harga tidak boleh diubah sembarangan
        self.__stok  = stok    # Private -- stok hanya boleh berkurang saat transaksi

    @property
    def harga(self):
        return self.__harga

    @property
    def stok(self):
        return self.__stok

    def kurangi_stok(self, jumlah):
        if jumlah > self.__stok:
            print(f"❌ Stok {self.nama} tidak cukup! Stok tersedia: {self.__stok}")
            return False
        self.__stok -= jumlah
        return True

    def tambah_stok(self, jumlah):
        if jumlah <= 0:
            print("❌ Jumlah penambahan stok harus lebih dari 0.")
            return
        self.__stok += jumlah
        print(f"✅ Stok {self.nama} berhasil ditambah {jumlah}. Stok sekarang: {self.__stok}")

    def __str__(self):
        return f"[{self.kode}] {self.nama:<15} Rp{self.__harga:>8,}  | Stok: {self.__stok}"

    def __repr__(self):
        return f"Produk(kode='{self.kode}', nama='{self.nama}', harga={self.__harga}, stok={self.__stok})"

In [145]:
class Inventaris:
    def __init__(self, nama_toko):
        self.nama_toko = nama_toko
        self.__daftar_produk = {}   # Private -- {kode: Object Produk}

    def tambah_produk(self, produk):
        if produk.kode in self.__daftar_produk:
            print(f"⚠️  Kode {produk.kode} sudah ada di inventaris.")
            return
        self.__daftar_produk[produk.kode] = produk
        print(f"✅ Produk '{produk.nama}' berhasil ditambahkan ke inventaris.")

    def cari_produk(self, kode):
        return self.__daftar_produk.get(kode, None)

    def tampilkan_inventaris(self):
        print(f"\n{'=' * 55}")
        print(f"{'📦 INVENTARIS TOKO: ' + self.nama_toko:^55}")
        print(f"{'=' * 55}")
        print(f"{'Kode':<6} {'Nama':<15} {'Harga':>12}  {'Stok':>6}")
        print(f"{'─' * 55}")
        for produk in self.__daftar_produk.values():
            print(produk)
        print(f"{'=' * 55}")
        print(f"Total jenis produk: {len(self.__daftar_produk)}")

In [146]:
class KasirToko(Inventaris):
    def __init__(self, nama_toko):
        super().__init__(nama_toko)
        self.__keranjang   = {}    # {kode: jumlah_beli}
        self.__total_bayar = 0
        self.__riwayat_transaksi = []

    def tambah_ke_keranjang(self, kode, jumlah):
        produk = self.cari_produk(kode)
        if produk is None:
            print(f"❌ Produk dengan kode '{kode}' tidak ditemukan.")
            return

        berhasil = produk.kurangi_stok(jumlah)
        if not berhasil:
            return

        if kode in self.__keranjang:
            self.__keranjang[kode] += jumlah
        else:
            self.__keranjang[kode] = jumlah

        subtotal = produk.harga * jumlah
        self.__total_bayar += subtotal
        print(f"🛒 {produk.nama} x{jumlah} ditambahkan ke keranjang. Subtotal: Rp{subtotal:,}")

    def tampilkan_keranjang(self):
        if not self.__keranjang:
            print("🛒 Keranjang masih kosong.")
            return

        print(f"\n{'=' * 55}")
        print(f"{'🛒 KERANJANG BELANJA':^55}")
        print(f"{'=' * 55}")
        print(f"{'Nama':<18} {'Harga':>10} {'Qty':>5} {'Subtotal':>12}")
        print(f"{'─' * 55}")

        for kode, jumlah in self.__keranjang.items():
            produk   = self.cari_produk(kode)
            subtotal = produk.harga * jumlah
            print(f"{produk.nama:<18} {produk.harga:>10,} {jumlah:>5} {subtotal:>12,}")

        print(f"{'─' * 55}")
        print(f"{'TOTAL':>40} {self.__total_bayar:>12,}")
        print(f"{'=' * 55}")

    def proses_pembayaran(self, uang_bayar):
        if not self.__keranjang:
            print("❌ Keranjang kosong! Tidak ada yang bisa dibayar.")
            return

        if uang_bayar < self.__total_bayar:
            print(f"❌ Uang tidak cukup! Kurang: Rp{self.__total_bayar - uang_bayar:,}")
            return

        kembalian = uang_bayar - self.__total_bayar

        print(f"\n{'=' * 55}")
        print(f"{'✅ PEMBAYARAN BERHASIL':^55}")
        print(f"{'=' * 55}")
        print(f"  Total belanja : Rp{self.__total_bayar:>10,}")
        print(f"  Uang bayar    : Rp{uang_bayar:>10,}")
        print(f"  Kembalian     : Rp{kembalian:>10,}")
        print(f"{'=' * 55}")
        print("  Terima kasih sudah berbelanja! 🙏")
        print(f"{'=' * 55}\n")

        # Simpan ke riwayat transaksi
        self.__riwayat_transaksi.append({
            "keranjang" : dict(self.__keranjang),
            "total"     : self.__total_bayar,
            "bayar"     : uang_bayar,
            "kembalian" : kembalian
        })

        # Reset keranjang untuk transaksi berikutnya
        self.__keranjang   = {}
        self.__total_bayar = 0

    def tampilkan_riwayat(self):
        if not self.__riwayat_transaksi:
            print("📋 Belum ada riwayat transaksi.")
            return

        print(f"\n{'=' * 55}")
        print(f"{'📋 RIWAYAT TRANSAKSI':^55}")
        print(f"{'=' * 55}")
        for i, transaksi in enumerate(self.__riwayat_transaksi, start=1):
            print(f"\nTransaksi #{i}")
            print(f"  Total bayar : Rp{transaksi['total']:,}")
            print(f"  Kembalian   : Rp{transaksi['kembalian']:,}")
        print(f"\n{'=' * 55}")
        print(f"Total transaksi selesai: {len(self.__riwayat_transaksi)}")
        print(f"{'=' * 55}")

In [147]:
# Buat Object KasirToko
toko = KasirToko("Toko Nalara")

# Buat beberapa produk
produk_list = [
    Produk("P001", "Pulpen",     3_000,  50),
    Produk("P002", "Buku Tulis", 15_000, 30),
    Produk("P003", "Penghapus",  2_000,  40),
    Produk("P004", "Pensil",     2_500,  60),
    Produk("P005", "Penggaris",  5_000,  20),
]

# Masukkan semua produk ke inventaris toko
for produk in produk_list:
    toko.tambah_produk(produk)

# Tampilkan inventaris awal
toko.tampilkan_inventaris()

✅ Produk 'Pulpen' berhasil ditambahkan ke inventaris.
✅ Produk 'Buku Tulis' berhasil ditambahkan ke inventaris.
✅ Produk 'Penghapus' berhasil ditambahkan ke inventaris.
✅ Produk 'Pensil' berhasil ditambahkan ke inventaris.
✅ Produk 'Penggaris' berhasil ditambahkan ke inventaris.

            📦 INVENTARIS TOKO: Toko Nalara             
Kode   Nama                   Harga    Stok
───────────────────────────────────────────────────────
[P001] Pulpen          Rp   3,000  | Stok: 50
[P002] Buku Tulis      Rp  15,000  | Stok: 30
[P003] Penghapus       Rp   2,000  | Stok: 40
[P004] Pensil          Rp   2,500  | Stok: 60
[P005] Penggaris       Rp   5,000  | Stok: 20
Total jenis produk: 5


In [148]:
print("🛍️  TRANSAKSI 1 — Pelanggan: Andi\n")

toko.tambah_ke_keranjang("P001", 3)   # 3 Pulpen
toko.tambah_ke_keranjang("P002", 2)   # 2 Buku Tulis
toko.tambah_ke_keranjang("P003", 1)   # 1 Penghapus

toko.tampilkan_keranjang()
toko.proses_pembayaran(uang_bayar=50_000)

🛍️  TRANSAKSI 1 — Pelanggan: Andi

🛒 Pulpen x3 ditambahkan ke keranjang. Subtotal: Rp9,000
🛒 Buku Tulis x2 ditambahkan ke keranjang. Subtotal: Rp30,000
🛒 Penghapus x1 ditambahkan ke keranjang. Subtotal: Rp2,000

                  🛒 KERANJANG BELANJA                  
Nama                    Harga   Qty     Subtotal
───────────────────────────────────────────────────────
Pulpen                  3,000     3        9,000
Buku Tulis             15,000     2       30,000
Penghapus               2,000     1        2,000
───────────────────────────────────────────────────────
                                   TOTAL       41,000

                 ✅ PEMBAYARAN BERHASIL                 
  Total belanja : Rp    41,000
  Uang bayar    : Rp    50,000
  Kembalian     : Rp     9,000
  Terima kasih sudah berbelanja! 🙏



In [149]:
print("🛍️  TRANSAKSI 2 — Pelanggan: Sari\n")

toko.tambah_ke_keranjang("P005", 5)    # 5 Penggaris
toko.tambah_ke_keranjang("P002", 50)   # stok tidak cukup, harusnya ditolak

toko.tampilkan_keranjang()
toko.proses_pembayaran(uang_bayar=30_000)

🛍️  TRANSAKSI 2 — Pelanggan: Sari

🛒 Penggaris x5 ditambahkan ke keranjang. Subtotal: Rp25,000
❌ Stok Buku Tulis tidak cukup! Stok tersedia: 28

                  🛒 KERANJANG BELANJA                  
Nama                    Harga   Qty     Subtotal
───────────────────────────────────────────────────────
Penggaris               5,000     5       25,000
───────────────────────────────────────────────────────
                                   TOTAL       25,000

                 ✅ PEMBAYARAN BERHASIL                 
  Total belanja : Rp    25,000
  Uang bayar    : Rp    30,000
  Kembalian     : Rp     5,000
  Terima kasih sudah berbelanja! 🙏



In [150]:
# Restok salah satu produk
print("📦 RESTOK BARANG")
produk_pulpen = toko.cari_produk("P001")
produk_pulpen.tambah_stok(100)

# Inventaris setelah transaksi & restok
toko.tampilkan_inventaris()

# Riwayat seluruh transaksi yang sudah selesai
toko.tampilkan_riwayat()

📦 RESTOK BARANG
✅ Stok Pulpen berhasil ditambah 100. Stok sekarang: 147

            📦 INVENTARIS TOKO: Toko Nalara             
Kode   Nama                   Harga    Stok
───────────────────────────────────────────────────────
[P001] Pulpen          Rp   3,000  | Stok: 147
[P002] Buku Tulis      Rp  15,000  | Stok: 28
[P003] Penghapus       Rp   2,000  | Stok: 39
[P004] Pensil          Rp   2,500  | Stok: 60
[P005] Penggaris       Rp   5,000  | Stok: 15
Total jenis produk: 5

                  📋 RIWAYAT TRANSAKSI                  

Transaksi #1
  Total bayar : Rp41,000
  Kembalian   : Rp9,000

Transaksi #2
  Total bayar : Rp25,000
  Kembalian   : Rp5,000

Total transaksi selesai: 2
